name: Build Node
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'uretra_network'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'

      - name: Build Node
        working-directory: uretra_network  # Работаем в корне проекта
        run: go build -o node.exe cmd/main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-executable
          path: uretra_network/node.exe