name: Build Node
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'uretra_network'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'

      - name: Build Windows
        working-directory: uretra_network
        run: go build -o node.exe cmd/main.go

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-node
          path: uretra_network/node.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'uretra_network'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'

      - name: Install UPX
        run: sudo apt-get update && sudo apt-get install -y upx-ucl

      - name: Build Linux
        working-directory: uretra_network
        run: |
          go build -o node cmd/main.go
          strip node
          upx --best node || echo "UPX compression failed"

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-node
          path: uretra_network/node