name: Build Node
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            extension: .exe
            artifact-name: windows-node
          - os: ubuntu-latest
            extension: ''
            artifact-name: linux-node
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'uretra_network'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'

      - name: Build Node
        working-directory: uretra_network
        run: |
          go build -o node${{ matrix.extension }} cmd/main.go
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            strip node
            upx --best node || echo "UPX not installed, skipping compression"
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: uretra_network/node${{ matrix.extension }}